/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jopo.jet.vista;

import com.jopo.jet.controlador.Actualizar;
import com.jopo.jet.controlador.AgregarArriba;
import com.jopo.jet.controlador.AgregarFila;
import com.jopo.jet.controlador.Controlador;
import com.jopo.jet.controlador.EliminarFilas;
import com.jopo.jet.model.Servicios;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import com.jopo.jet.model.Equipo;
import com.jopo.jet.model.ImportarCSV;
import com.jopo.jet.model.ListaEquipos;
import com.jopo.jet.model.ExportarCSV;
import com.jopo.jet.controlador.Importacion;
import com.jopo.jet.controlador.Totalizar;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.jopo.jet.model.ModeloExcel;
import com.jopo.jet.model.ModeloTabla;
import com.jopo.jet.model.PegarExcel;
import com.jopo.jet.model.SeleccionArchivo;

/**
 *
 * @author Joel
 */
public class pFrame extends javax.swing.JFrame {

    /**
     * Creates new form pFrame
     */
    ArrayList<Equipo> listaFaltantes = new ArrayList<Equipo>();
    ArrayList<Equipo> listado = new ArrayList<Equipo>();

    ListaEquipos listaBorrador = new ListaEquipos();
    ListaEquipos listaListado = new ListaEquipos();
    ModeloTabla mdBorrador = new ModeloTabla();
    ModeloTabla mdFaltantes = new ModeloTabla();
    ModeloTabla mdBase = new ModeloTabla();
    ModeloTabla mdListado = new ModeloTabla();

    public pFrame() {
        initComponents();
        txtCargando.setVisible(false);
        txtPorcentaje.setVisible(false);
        jProgressBar1.setVisible(false);
        //PegarExcel pegarExcel=new PegarExcel(tbBase);
    }

//    @Override
//    public Image getIconImage() {
//       Image retValue = Toolkit.getDefaultToolkit().
//                getImage(ClassLoader.getSystemResource("scr/main/java/com/jopo/jet/img/icono.png"));
//
//        return retValue;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jBorrador = new javax.swing.JPanel();
        jBotonera = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnTotalizar = new javax.swing.JButton();
        txtCargando = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        txtPorcentaje = new javax.swing.JLabel();
        jTablaBorrador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBorrador = new javax.swing.JTable();
        jDetallesBorrador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalImportados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFilasError = new javax.swing.JTextField();
        jFaltantes = new javax.swing.JPanel();
        jBotoneraFaltantes = new javax.swing.JPanel();
        btnTotalizarFaltantes = new javax.swing.JButton();
        btnAgregarFilaFaltantes = new javax.swing.JButton();
        btnEliminarFilasFaltantes = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTablaFaltantes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFaltantes = new javax.swing.JTable();
        jTablaBase = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbBase = new javax.swing.JTable();
        jBotoneraBase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnAgregarArriba = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jDetallesFaltantes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantFaltantes = new javax.swing.JTextField();
        txtTotalFaltantes = new javax.swing.JTextField();
        txtFilasErrorFaltantes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jListado = new javax.swing.JPanel();
        jTablaBorrador1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbListado = new javax.swing.JTable();
        jDetallesListado = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuGuardarComo = new javax.swing.JMenuItem();
        jMenuImprimir = new javax.swing.JMenuItem();
        jMenuCerrar = new javax.swing.JMenuItem();
        jMenuImportar = new javax.swing.JMenu();
        jMenuImportarCSV = new javax.swing.JMenuItem();
        jMenuExportar = new javax.swing.JMenu();
        jMenuExportarAscent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JETotalizador v1.1");
        setIconImage(getIconImage());

        jBotonera.setBackground(new java.awt.Color(204, 204, 204));

        btnAgregar.setText("Agregar Fila");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnTotalizar.setText("Totalizar");
        btnTotalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalizarActionPerformed(evt);
            }
        });

        txtCargando.setText("Cargando...");

        txtPorcentaje.setText("100%");

        javax.swing.GroupLayout jBotoneraLayout = new javax.swing.GroupLayout(jBotonera);
        jBotonera.setLayout(jBotoneraLayout);
        jBotoneraLayout.setHorizontalGroup(
            jBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTotalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(txtCargando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jBotoneraLayout.setVerticalGroup(
            jBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotoneraLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargando, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnTotalizar, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablaBorrador.setBackground(new java.awt.Color(204, 204, 204));

        tbBorrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descripción", "Cantidad", "Unidad", "Catalogo", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbBorrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbBorradorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbBorrador);
        if (tbBorrador.getColumnModel().getColumnCount() > 0) {
            tbBorrador.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbBorrador.getColumnModel().getColumn(1).setPreferredWidth(600);
            tbBorrador.getColumnModel().getColumn(2).setPreferredWidth(60);
            tbBorrador.getColumnModel().getColumn(3).setPreferredWidth(60);
            tbBorrador.getColumnModel().getColumn(4).setPreferredWidth(180);
            tbBorrador.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jTablaBorradorLayout = new javax.swing.GroupLayout(jTablaBorrador);
        jTablaBorrador.setLayout(jTablaBorradorLayout);
        jTablaBorradorLayout.setHorizontalGroup(
            jTablaBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaBorradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jTablaBorradorLayout.setVerticalGroup(
            jTablaBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaBorradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDetallesBorrador.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Total de importados:");

        txtTotalImportados.setEditable(false);

        jLabel4.setText("Cantidad Total:");

        txtCantTotal.setEditable(false);

        jLabel5.setText("Items en error:");

        txtFilasError.setEditable(false);

        javax.swing.GroupLayout jDetallesBorradorLayout = new javax.swing.GroupLayout(jDetallesBorrador);
        jDetallesBorrador.setLayout(jDetallesBorradorLayout);
        jDetallesBorradorLayout.setHorizontalGroup(
            jDetallesBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetallesBorradorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jDetallesBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDetallesBorradorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDetallesBorradorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalImportados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFilasError)
                .addContainerGap())
        );
        jDetallesBorradorLayout.setVerticalGroup(
            jDetallesBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetallesBorradorLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jDetallesBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalImportados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtFilasError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDetallesBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jBorradorLayout = new javax.swing.GroupLayout(jBorrador);
        jBorrador.setLayout(jBorradorLayout);
        jBorradorLayout.setHorizontalGroup(
            jBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBorradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTablaBorrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDetallesBorrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jBorradorLayout.setVerticalGroup(
            jBorradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBorradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTablaBorrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDetallesBorrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Borrador", jBorrador);

        jBotoneraFaltantes.setBackground(new java.awt.Color(204, 204, 204));

        btnTotalizarFaltantes.setText("Totalizar");
        btnTotalizarFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalizarFaltantesActionPerformed(evt);
            }
        });

        btnAgregarFilaFaltantes.setText("Agregar Fila");
        btnAgregarFilaFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaFaltantesActionPerformed(evt);
            }
        });

        btnEliminarFilasFaltantes.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarFilasFaltantes.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFilasFaltantes.setText("Eliminar");
        btnEliminarFilasFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilasFaltantesActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LISTA DE EQUIPOS FALTANTES");

        javax.swing.GroupLayout jBotoneraFaltantesLayout = new javax.swing.GroupLayout(jBotoneraFaltantes);
        jBotoneraFaltantes.setLayout(jBotoneraFaltantesLayout);
        jBotoneraFaltantesLayout.setHorizontalGroup(
            jBotoneraFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotoneraFaltantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTotalizarFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarFilaFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarFilasFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jBotoneraFaltantesLayout.setVerticalGroup(
            jBotoneraFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotoneraFaltantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBotoneraFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalizarFaltantes)
                    .addComponent(btnAgregarFilaFaltantes)
                    .addComponent(btnEliminarFilasFaltantes)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablaFaltantes.setBackground(new java.awt.Color(204, 204, 204));

        tbFaltantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descripción", "Cantidad", "Unidad", "Catalogo", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbFaltantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbFaltantesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbFaltantes);
        if (tbFaltantes.getColumnModel().getColumnCount() > 0) {
            tbFaltantes.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbFaltantes.getColumnModel().getColumn(1).setPreferredWidth(600);
            tbFaltantes.getColumnModel().getColumn(2).setPreferredWidth(60);
            tbFaltantes.getColumnModel().getColumn(3).setPreferredWidth(60);
            tbFaltantes.getColumnModel().getColumn(4).setPreferredWidth(180);
            tbFaltantes.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jTablaFaltantesLayout = new javax.swing.GroupLayout(jTablaFaltantes);
        jTablaFaltantes.setLayout(jTablaFaltantesLayout);
        jTablaFaltantesLayout.setHorizontalGroup(
            jTablaFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaFaltantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTablaFaltantesLayout.setVerticalGroup(
            jTablaFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaFaltantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTablaBase.setBackground(new java.awt.Color(204, 204, 204));

        tbBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descripción", "Unidad", "Catalogo", "Fabricante", "Cod_fab"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbBase);
        if (tbBase.getColumnModel().getColumnCount() > 0) {
            tbBase.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbBase.getColumnModel().getColumn(1).setPreferredWidth(600);
            tbBase.getColumnModel().getColumn(2).setPreferredWidth(60);
            tbBase.getColumnModel().getColumn(3).setPreferredWidth(180);
            tbBase.getColumnModel().getColumn(4).setPreferredWidth(200);
            tbBase.getColumnModel().getColumn(5).setPreferredWidth(180);
        }

        javax.swing.GroupLayout jTablaBaseLayout = new javax.swing.GroupLayout(jTablaBase);
        jTablaBase.setLayout(jTablaBaseLayout);
        jTablaBaseLayout.setHorizontalGroup(
            jTablaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTablaBaseLayout.setVerticalGroup(
            jTablaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBotoneraBase.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Código:");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel2.setText("Descripción:");

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
        });

        btnAgregarArriba.setText("Agregar Arriba");
        btnAgregarArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArribaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BASE DE EQUIPOS ENERO 2019");

        javax.swing.GroupLayout jBotoneraBaseLayout = new javax.swing.GroupLayout(jBotoneraBase);
        jBotoneraBase.setLayout(jBotoneraBaseLayout);
        jBotoneraBaseLayout.setHorizontalGroup(
            jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotoneraBaseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(txtCodigo))
                .addGap(27, 27, 27)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBotoneraBaseLayout.setVerticalGroup(
            jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotoneraBaseLayout.createSequentialGroup()
                .addGroup(jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBotoneraBaseLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jBotoneraBaseLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jBotoneraBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarArriba)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel9))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jDetallesFaltantes.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Total de Faltantes:");

        jLabel7.setText("Cantidad Total:");

        txtCantFaltantes.setEditable(false);

        txtTotalFaltantes.setEditable(false);

        txtFilasErrorFaltantes.setEditable(false);

        jLabel8.setText("Items en error:");

        javax.swing.GroupLayout jDetallesFaltantesLayout = new javax.swing.GroupLayout(jDetallesFaltantes);
        jDetallesFaltantes.setLayout(jDetallesFaltantesLayout);
        jDetallesFaltantesLayout.setHorizontalGroup(
            jDetallesFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetallesFaltantesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jDetallesFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDetallesFaltantesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDetallesFaltantesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFilasErrorFaltantes)
                .addContainerGap())
        );
        jDetallesFaltantesLayout.setVerticalGroup(
            jDetallesFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetallesFaltantesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jDetallesFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtFilasErrorFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDetallesFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jFaltantesLayout = new javax.swing.GroupLayout(jFaltantes);
        jFaltantes.setLayout(jFaltantesLayout);
        jFaltantesLayout.setHorizontalGroup(
            jFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFaltantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotoneraFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTablaBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotoneraBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDetallesFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFaltantesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTablaFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jFaltantesLayout.setVerticalGroup(
            jFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFaltantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotoneraFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(jBotoneraBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTablaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDetallesFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jFaltantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFaltantesLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jTablaFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(430, 430, 430)))
        );

        jTabbedPane1.addTab("Faltantes", jFaltantes);

        jTablaBorrador1.setBackground(new java.awt.Color(204, 204, 204));

        tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descripción", "Cantidad", "Unidad", "Catalogo", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListadoKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbListado);
        if (tbListado.getColumnModel().getColumnCount() > 0) {
            tbListado.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbListado.getColumnModel().getColumn(1).setPreferredWidth(600);
            tbListado.getColumnModel().getColumn(2).setPreferredWidth(60);
            tbListado.getColumnModel().getColumn(3).setPreferredWidth(60);
            tbListado.getColumnModel().getColumn(4).setPreferredWidth(180);
            tbListado.getColumnModel().getColumn(5).setResizable(false);
            tbListado.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jTablaBorrador1Layout = new javax.swing.GroupLayout(jTablaBorrador1);
        jTablaBorrador1.setLayout(jTablaBorrador1Layout);
        jTablaBorrador1Layout.setHorizontalGroup(
            jTablaBorrador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaBorrador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTablaBorrador1Layout.setVerticalGroup(
            jTablaBorrador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaBorrador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDetallesListado.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDetallesListadoLayout = new javax.swing.GroupLayout(jDetallesListado);
        jDetallesListado.setLayout(jDetallesListadoLayout);
        jDetallesListadoLayout.setHorizontalGroup(
            jDetallesListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
        );
        jDetallesListadoLayout.setVerticalGroup(
            jDetallesListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jListadoLayout = new javax.swing.GroupLayout(jListado);
        jListado.setLayout(jListadoLayout);
        jListadoLayout.setHorizontalGroup(
            jListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDetallesListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTablaBorrador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jListadoLayout.setVerticalGroup(
            jListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTablaBorrador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDetallesListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado", jListado);

        jMenuArchivo.setText("Archivo");

        jMenuNuevo.setMnemonic('N');
        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuNuevo);

        jMenuAbrir.setMnemonic('A');
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuAbrir);

        jMenuGuardar.setMnemonic('G');
        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuGuardar);

        jMenuGuardarComo.setText("Guardar como");
        jMenuArchivo.add(jMenuGuardarComo);

        jMenuImprimir.setMnemonic('I');
        jMenuImprimir.setText("Imprimir");
        jMenuArchivo.add(jMenuImprimir);

        jMenuCerrar.setMnemonic('C');
        jMenuCerrar.setText("Cerrar");
        jMenuArchivo.add(jMenuCerrar);

        jMenuBar1.add(jMenuArchivo);

        jMenuImportar.setText("Importar");

        jMenuImportarCSV.setText("Importar CSV");
        jMenuImportarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImportarCSVActionPerformed(evt);
            }
        });
        jMenuImportar.add(jMenuImportarCSV);

        jMenuBar1.add(jMenuImportar);

        jMenuExportar.setText("Exportar");

        jMenuExportarAscent.setText("Exportar Ascent");
        jMenuExportarAscent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExportarAscentActionPerformed(evt);
            }
        });
        jMenuExportar.add(jMenuExportarAscent);

        jMenuBar1.add(jMenuExportar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        EliminarFilas eliminar = new EliminarFilas(tbBorrador, txtTotalImportados, txtFilasError, txtCantTotal);
        eliminar.ejecutar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        AgregarFila agregar = new AgregarFila(tbBorrador, txtTotalImportados, txtFilasError, txtCantTotal);
        agregar.ejecutar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnTotalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalizarActionPerformed
        Totalizar totalizar = new Totalizar(tbBorrador, tbFaltantes, tbListado, txtTotalImportados, txtFilasError, txtCantTotal);
        totalizar.ejecutar();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnTotalizarActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        ArrayList<Equipo> listaBase = new ArrayList<Equipo>();
        int i = 0;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Servicios servicio = new Servicios();
            txtDescripcion.setText("");
            try {

                ResultSet rs = servicio.buscarProductos(txtCodigo.getText());
                while (rs.next()) {
                    Equipo eq = new Equipo();
                    i++;
                    eq.setItem(i);
                    eq.setCat(rs.getString("CODIGO"));
                    eq.setDesc(rs.getString("NOMBRE"));
                    eq.setUnd(rs.getString("UNIDAD"));
                    eq.setFab(rs.getString("MARCA"));
                    eq.setCod_fab(rs.getString("CODIGO_FAB"));
                    eq.setFamilia(rs.getString("FAMILIA"));
                    eq.setSub_familia(rs.getString("SUB_FAMILIA"));
                    listaBase.add(eq);
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
            mdBase.limpiar(tbBase);
            mdBase.rellenarBase(listaBase);
            tbBase.setModel(mdBase.getModel());
        }

    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        ArrayList<Equipo> listaBase = new ArrayList<Equipo>();
        int i = 0;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Servicios servicio = new Servicios();
            txtCodigo.setText("");
            try {

                ResultSet rs = servicio.buscarDescripcion(txtDescripcion.getText());
                while (rs.next()) {
                    Equipo eq = new Equipo();
                    i++;
                    eq.setItem(i);
                    eq.setCat(rs.getString("CODIGO"));
                    eq.setDesc(rs.getString("NOMBRE"));
                    eq.setUnd(rs.getString("UNIDAD"));
                    eq.setFab(rs.getString("MARCA"));
                    eq.setCod_fab(rs.getString("CODIGO_FAB"));
                    eq.setFamilia(rs.getString("FAMILIA"));
                    eq.setSub_familia(rs.getString("SUB_FAMILIA"));
                    listaBase.add(eq);
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
            mdBase.limpiar(tbBase);
            mdBase.rellenarBase(listaBase);
            tbBase.setModel(mdBase.getModel());
        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void btnTotalizarFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalizarFaltantesActionPerformed
        Totalizar totalizar = new Totalizar(tbFaltantes, tbFaltantes, tbListado, txtTotalFaltantes, txtFilasErrorFaltantes, txtCantFaltantes);
        totalizar.ejecutar();
    }//GEN-LAST:event_btnTotalizarFaltantesActionPerformed

    private void btnAgregarFilaFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaFaltantesActionPerformed
        AgregarFila agregar = new AgregarFila(tbFaltantes, txtTotalFaltantes, txtFilasErrorFaltantes, txtCantFaltantes);
        agregar.ejecutar();
    }//GEN-LAST:event_btnAgregarFilaFaltantesActionPerformed

    private void btnEliminarFilasFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilasFaltantesActionPerformed
        EliminarFilas eliminar = new EliminarFilas(tbFaltantes, txtTotalFaltantes, txtFilasErrorFaltantes, txtCantFaltantes);
        eliminar.ejecutar();
    }//GEN-LAST:event_btnEliminarFilasFaltantesActionPerformed

    private void btnAgregarArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArribaActionPerformed
        AgregarArriba agregar = new AgregarArriba(tbFaltantes, tbBase, txtTotalFaltantes, txtFilasErrorFaltantes, txtCantFaltantes);
        agregar.ejecutar();
    }//GEN-LAST:event_btnAgregarArribaActionPerformed

    private void tbBorradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbBorradorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Se presiono enter");
            Actualizar actualizar = new Actualizar(tbBorrador, txtTotalImportados, txtFilasError, txtCantTotal);
            actualizar.ejecutar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            System.out.println("Se presiono delete");
            EliminarFilas eliminar = new EliminarFilas(tbBorrador, txtTotalImportados, txtFilasError, txtCantTotal);
            eliminar.ejecutar();
        }


    }//GEN-LAST:event_tbBorradorKeyPressed

    private void tbFaltantesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbFaltantesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Se presiono enter");
            Actualizar actualizar = new Actualizar(tbFaltantes, txtTotalFaltantes, txtFilasError, txtCantFaltantes);
            actualizar.ejecutar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            System.out.println("Se presiono delete");
            EliminarFilas eliminar = new EliminarFilas(tbFaltantes, txtTotalFaltantes, txtFilasError, txtCantFaltantes);
            eliminar.ejecutar();
        }
    }//GEN-LAST:event_tbFaltantesKeyPressed

    private void tbListadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Se presiono enter");
            Actualizar actualizar = new Actualizar(tbListado, txtTotalFaltantes, txtFilasError, txtCantFaltantes);
            actualizar.ejecutar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            System.out.println("Se presiono delete");
            EliminarFilas eliminar = new EliminarFilas(tbListado, txtTotalFaltantes, txtFilasError, txtCantFaltantes);
            eliminar.ejecutar();
        }
    }//GEN-LAST:event_tbListadoKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ArrayList<Equipo> listaBase = new ArrayList<Equipo>();
        int i = 0;
        Servicios servicio = new Servicios();
        txtDescripcion.setText("");
        try {

            ResultSet rs = servicio.buscarProductos(txtCodigo.getText());
            while (rs.next()) {
                Equipo eq = new Equipo();
                i++;
                eq.setItem(i);
                eq.setCat(rs.getString("CODIGO"));
                eq.setDesc(rs.getString("NOMBRE"));
                eq.setUnd(rs.getString("UNIDAD"));
                eq.setFab(rs.getString("MARCA"));
                eq.setCod_fab(rs.getString("CODIGO_FAB"));
                eq.setFamilia(rs.getString("FAMILIA"));
                eq.setSub_familia(rs.getString("SUB_FAMILIA"));
                listaBase.add(eq);
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
        mdBase.limpiar(tbBase);
        mdBase.rellenarBase(listaBase);
        tbBase.setModel(mdBase.getModel());

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jMenuImportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImportarCSVActionPerformed
        Importacion importacion = new Importacion(tbBorrador, txtTotalImportados, txtFilasError,
                txtCargando, txtPorcentaje, jProgressBar1, txtCantTotal);
        importacion.ejecutar();
    }//GEN-LAST:event_jMenuImportarCSVActionPerformed

    private void jMenuExportarAscentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExportarAscentActionPerformed
        ModeloExcel modelo = new ModeloExcel();
        SeleccionArchivo sa = new SeleccionArchivo("xls");
        JTable tablaTemp = new JTable();
        String ruta, ruta1;
        ruta = sa.getOutputPath();
        ruta1 = ruta + ".xls";
        listaListado.recogerDatos(tbListado);
        System.out.println("ESTA ES EL LISTADO A EXPORTAR: ");
        System.out.println(listaListado.toString());
        System.out.println("FIN DEL LISTADO A EXPORTAR");
        try {
            File archivo = new File(ruta1);
            tablaTemp.setModel(mdListado.modeloAscent(listaListado.getLista()));
            modelo.ExportarAscent(archivo, tbListado);
            JOptionPane.showMessageDialog(null, "Exportación exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al exportar: " + e);
        }
    }//GEN-LAST:event_jMenuExportarAscentActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Se borraran todas las listas\n¿Estas seguro?",
                "Crear Nuevo",JOptionPane.YES_NO_OPTION);
        if (n==0) {
            mdBase.limpiar(tbBorrador);
            mdBase.limpiar(tbFaltantes);
            mdBase.limpiar(tbListado);
            listaBorrador.limpiar();
            listaListado.limpiar();
            listaFaltantes.clear();
        }
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed

        listaBorrador.recogerDatos(tbBorrador);
        //listaFaltantes.recogerDatos(tbFaltantes);
        listaListado.recogerDatos(tbListado);
        
        SeleccionArchivo sa = new SeleccionArchivo("csv");
        String ruta, ruta1, ruta2;
        ruta = sa.getOutputPath();
        ruta1 = ruta + ".csv";
        ruta2 = ruta + "_Listado.csv";
        ExportarCSV guardarBorrador=new ExportarCSV(ruta1,listaBorrador.getLista());
        ExportarCSV guardarListado=new ExportarCSV(ruta2,listaListado.getLista());
        try {
            guardarBorrador.exportar(ruta1);
            guardarListado.exportar(ruta2);
            
        } catch (IOException ex) {
            Logger.getLogger(pFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
                Importacion abrirBorrador = new Importacion(tbBorrador, txtTotalImportados, txtFilasError,
                txtCargando, txtPorcentaje, jProgressBar1, txtCantTotal);
                Importacion abrirListado = new Importacion(tbListado, txtTotalImportados, txtFilasError,
                txtCargando, txtPorcentaje, jProgressBar1, txtCantTotal);
        abrirBorrador.ejecutar();
        abrirListado.ejecutar();
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarArriba;
    private javax.swing.JButton btnAgregarFilaFaltantes;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarFilasFaltantes;
    private javax.swing.JButton btnTotalizar;
    private javax.swing.JButton btnTotalizarFaltantes;
    private javax.swing.JPanel jBorrador;
    private javax.swing.JPanel jBotonera;
    private javax.swing.JPanel jBotoneraBase;
    private javax.swing.JPanel jBotoneraFaltantes;
    private javax.swing.JPanel jDetallesBorrador;
    private javax.swing.JPanel jDetallesFaltantes;
    private javax.swing.JPanel jDetallesListado;
    private javax.swing.JPanel jFaltantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jListado;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCerrar;
    private javax.swing.JMenu jMenuExportar;
    private javax.swing.JMenuItem jMenuExportarAscent;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuGuardarComo;
    private javax.swing.JMenu jMenuImportar;
    private javax.swing.JMenuItem jMenuImportarCSV;
    private javax.swing.JMenuItem jMenuImprimir;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jTablaBase;
    private javax.swing.JPanel jTablaBorrador;
    private javax.swing.JPanel jTablaBorrador1;
    private javax.swing.JPanel jTablaFaltantes;
    private javax.swing.JTable tbBase;
    private javax.swing.JTable tbBorrador;
    private javax.swing.JTable tbFaltantes;
    private javax.swing.JTable tbListado;
    private javax.swing.JTextField txtCantFaltantes;
    private javax.swing.JTextField txtCantTotal;
    private javax.swing.JLabel txtCargando;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFilasError;
    private javax.swing.JTextField txtFilasErrorFaltantes;
    private javax.swing.JLabel txtPorcentaje;
    private javax.swing.JTextField txtTotalFaltantes;
    private javax.swing.JTextField txtTotalImportados;
    // End of variables declaration//GEN-END:variables
}
